### ISSUE TITLE
learn.sh NullPointerException during PostProcessing

### ISSUE THREAD

**Issue by rpietzsch** [AKSW/FOX#7]
Not sure if misconfiguration or issue, please advice:

Fresh clone (e83b0f0b5ee91a3c3bd82ecf723e01ef4ee3cf74) +  build on ubnutu 14.04.
Only change I did to fox-properties(-dist) was enabling of org.aksw.fox.nerlearner.FoxClassifier.training. 

Learning raises a NullPointerException:
```
18:30:13  INFO [Thread-2] (AbstractNER.java:logMsg:140) - NERIllinoisExtended(token):
18:30:13  INFO [Thread-2] (AbstractNER.java:logMsg:141) - 5503 LOCs found
18:30:13  INFO [Thread-2] (AbstractNER.java:logMsg:142) - 10901 ORGs found
18:30:13  INFO [Thread-2] (AbstractNER.java:logMsg:143) - 5828 PERs found
18:30:13  INFO [Thread-2] (AbstractNER.java:logMsg:144) - 22232 total found
18:31:08  INFO [main] (PostProcessing.java:<init>:45) - PostProcessing ...
java.lang.NullPointerException
	at org.aksw.fox.data.TokenManager.repairEntities(TokenManager.java:94)
	at org.aksw.fox.nerlearner.PostProcessing.<init>(PostProcessing.java:51)
	at org.aksw.fox.nerlearner.FoxClassifier.training(FoxClassifier.java:177)
	at org.aksw.fox.MainFox.training(MainFox.java:192)
	at org.aksw.fox.MainFox.main(MainFox.java:109)
```

**Comment by renespeck** [comment]
Thanks for the report. 

Try to set 'org.aksw.fox.nertools.FoxNERTools.foxNERLifeTime' to a higher value in the 'fox-properties' file.
